# Generated by Django 2.2.4 on 2019-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
