# Generated by Django 2.2.4 on 2019-09-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='bathroom',
            field=models.IntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')], default=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='bedrooms',
            field=models.IntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='living_rom',
            field=models.IntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')], default=0),
            preserve_default=False,
        ),
    ]
