# Generated by Django 2.2.4 on 2019-09-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackhome', '0002_auto_20190901_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
