# Generated by Django 2.2.4 on 2019-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackhome', '0004_apartment_equipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
