# Generated by Django 2.2.4 on 2019-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackhome', '0005_apartment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
